In [1]:
## 다층 퍼셉트론 - XOR - Tensorflow 1.x

In [2]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정

seed = 2002
np.random.seed(seed)
tf.set_random_seed(seed)

In [5]:
# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0]).reshape(-1, 1)
print(x_data.shape, y_data.shape)

(4, 2) (4, 1)


In [6]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [7]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32) # 가중치 정하기
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)    # bise 정하기
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)                      # 정했던 걸로 레이어 만들기

In [8]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [9]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [10]:
# Optimizer - Adam
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [11]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [12]:
# 학습

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # Weight, bias
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 0.82351696
1000 0.34711188
2000 0.3467303
3000 0.34664235
4000 0.34660873
5000 0.34659302
6000 0.34658462
7000 0.34658062
8000 0.3465783
9000 0.3465771
10000 0.3465762

Hypothesis:
[[1.1305552e-06]
 [9.9999106e-01]
 [4.9999881e-01]
 [4.9999905e-01]] 
Predicted:
[[0.]
 [1.]
 [0.]
 [0.]] 
Accuracy:
0.75

W1:
[[-19.482704  21.711987]
 [-11.867702  -9.385075]] 
b1:
[3.1644661 4.308641 ] 
W2:
[[-14.433004]
 [-11.701063]]
b1:
[11.701059]
